### PR TITLE
feat(health-sdk):Set "powered by Gini" removable from payment component

### PR DESCRIPTION
**Pull request by llevente**

### CODE REVIEW

**Review by a-szotyori — CHANGES_REQUESTED** [review]
Thank you, Lenci! Looks great I have only two requests:
1.  Please change the git commit message to match our [git commit template](https://github.com/gini/gini-mobile-android/blob/main/.git-stuff/commit-msg-template.txt) (it's ok to use rebase in feature branches to rewrite the history):
```
feat(health-sdk): Set "powered by Gini" removable from payment component

IPC-293
```
2. Please add a unit test for this. You can use Robolectric, if needed.

Thank you!

**Review by danicretu — COMMENTED** [review]
Looks great, thank you! The only comment I have is the same as Alpár's about the git commit message.

**Review by a-szotyori — APPROVED** [review]
Thank you for adding the test! I approved the PR since the code is good and it can go to QA.

**Comment by llevente** [comment]
@a-szotyori  @danicretu  Commit message is fixed, test added for checking if the view if hidden with this option.

**Comment by llevente** [comment]
@a-szotyori  @danicretu  Commit message is also fixed, so the rule is kept. Moving forward to QA as Alpar said in the previous comment

**Pull request merged**
