### PR TITLE
Pp 74 jira ticket post

### PR DESCRIPTION
**Pull request by GeraltRiv**
https://github.com/gini/gini-mobile-android/actions/runs/12084769854
THis works fine
In the task we can see links posted by bot. We need to change info in github secrets, to make some bot post this comments, not me
https://ginis.atlassian.net/browse/PP-74

### CODE REVIEW

**Review by danicretu — APPROVED** [review]
Looks good, thank you!

**Review by llevente — APPROVED** [review]

**Review by abolfazlimahdi — APPROVED** [review]
Looks good. Did you remove publishing to AppCenter from the workflows? If everything is working fine in Firebase, please remove AppCenter as well (ask Nadya before removing).  Thank you!

**Comment by GeraltRiv** [comment]
> Looks good. Did you remove publishing to AppCenter from the workflows? If everything is working fine in Firebase, please remove AppCenter as well (ask Nadya before removing). Thank you!

I made it optional removed all push triggers. I think we can delete it when app center will be closed.

**Comment by abolfazlimahdi** [comment]
> > Looks good. Did you remove publishing to AppCenter from the workflows? If everything is working fine in Firebase, please remove AppCenter as well (ask Nadya before removing). Thank you!
> 
> I made it optional removed all push triggers. I think we can delete it when app center will be closed.

Looks great. Thank you!

**Review by zladzeyka — APPROVED** [review]

**Pull request merged**
